CREATE DATABASE IPBEACH;
USE IPBEACH;

CREATE TABLE USUARIO(
    IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SENHA varchar(20) NOT NULL,
    DATADECRIACAO DATE NOT NULL
);

CREATE TABLE RESERVA(
    IDRESERVA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50),
    TELEFONE CHAR(14) NOT NULL,
    DATAADENDAMENTO DATE NOT NULL,
    DATAAGENDADA DATE NOT NULL,
    HORA CHAR(2) NOT NULL,
);